name: client
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.0.0-228.0.dev <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    shared_preferences: ^2.1.1
    flutter_native_splash: ^2.2.18
    flutter_launcher_icons: ^0.13.1
    dio: ^5.1.2
    retrofit: ^4.0.1
    json_annotation: ^4.8.1
    kakao_map_plugin: ^0.1.4
    geolocator: ^9.0.2
    credit_card_scanner: ^1.0.0
    bottom_sheet: ^3.1.2
    rflutter_alert: ^2.0.7
    latlong2: ^0.8.2
    url_launcher: ^6.1.11

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "asset/logo/logo.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
        generate: true
        image_path: "asset/logo/logo.png"

    windows:
        generate: true
        icon_size: 48 # min:48, max:256, default: 48
    macos:
        generate: true
        image_path: "asset/logo/logo.png"

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    build_runner: ^2.3.3
    json_serializable: ^6.6.1
    retrofit_generator: ^6.0.0+1

flutter:
    uses-material-design: true
    assets:
        - asset/fonts/
        - asset/bank/
        - asset/categorylist/
        - asset/character/
        - asset/kindstore/
        - asset/store/
        - asset/logo/
        - asset/chating/
        - asset/agree/
    fonts:
        - family: NanumSquare
          fonts:
              - asset: asset/fonts/NanumSquareR.ttf
              - asset: asset/fonts/NanumSquareB.ttf
